[server]
headless = true
port = 8501
enableCORS = false

[theme]
base="light"
primaryColor = "#00bcd4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"
